const fs = require('fs');

// Create sample ride data for date range March 23 - April 14, 2025
const rides = [
  {
    id: "1001",
    driver_id: "user123",
    departure_location: "Vancouver Downtown",
    destination: "Whistler Blackcomb",
    ski_resort: "Whistler Blackcomb",
    pickup_zone: "Downtown Transit Center",
    departure_time: "2025-03-23T07:30:00Z",
    return_time: "2025-03-23T18:00:00Z",
    available_seats: 3,
    price: 45,
    description: "Morning ride to Whistler. Coffee provided!",
    car_make: "Subaru",
    car_model: "Outback",
    gear_space: "Medium - can fit 3 sets of skis",
    created_at: "2025-03-01T12:00:00Z"
  },
  {
    id: "1002",
    driver_id: "user456",
    departure_location: "Seattle",
    destination: "Crystal Mountain",
    ski_resort: "Crystal Mountain",
    pickup_zone: "Pike Place Market",
    departure_time: "2025-03-24T06:45:00Z",
    return_time: "2025-03-24T17:30:00Z",
    available_seats: 4,
    price: 35,
    description: "Early start for fresh powder. Good vibes only.",
    car_make: "Toyota",
    car_model: "4Runner",
    gear_space: "Large - room for boards and skis",
    created_at: "2025-03-02T09:30:00Z"
  },
  {
    id: "1003",
    driver_id: "user789",
    departure_location: "Portland",
    destination: "Mount Hood",
    ski_resort: "Mount Hood Meadows",
    pickup_zone: "Pioneer Courthouse Square",
    departure_time: "2025-03-25T08:00:00Z",
    return_time: "2025-03-25T19:00:00Z",
    available_seats: 2,
    price: 30,
    description: "Regular weekend trip. Split gas and parking.",
    car_make: "Honda",
    car_model: "CR-V",
    gear_space: "Medium - 2 snowboards or 2 pairs of skis",
    created_at: "2025-03-05T14:20:00Z"
  },
  {
    id: "1004",
    driver_id: "user321",
    departure_location: "North Vancouver",
    destination: "Cypress Mountain",
    ski_resort: "Cypress Mountain",
    pickup_zone: "Lonsdale Quay",
    departure_time: "2025-03-26T15:00:00Z",
    return_time: "2025-03-26T21:30:00Z",
    available_seats: 3,
    price: 25,
    description: "Afternoon session at Cypress. Quick trip!",
    car_make: "Jeep",
    car_model: "Cherokee",
    gear_space: "Medium - can fit 3-4 sets of gear",
    created_at: "2025-03-07T11:15:00Z"
  },
  {
    id: "1005",
    driver_id: "user654",
    departure_location: "Burnaby",
    destination: "Grouse Mountain",
    ski_resort: "Grouse Mountain",
    pickup_zone: "Metrotown Mall",
    departure_time: "2025-03-27T09:15:00Z",
    return_time: "2025-03-27T16:45:00Z",
    available_seats: 2,
    price: 20,
    description: "Chill day at Grouse. Beginners welcome!",
    car_make: "Mazda",
    car_model: "CX-5",
    gear_space: "Small - 2 pairs of skis max",
    created_at: "2025-03-08T18:40:00Z"
  },
  {
    id: "1006",
    driver_id: "user987",
    departure_location: "Surrey",
    destination: "Mount Seymour",
    ski_resort: "Mount Seymour",
    pickup_zone: "Central City",
    departure_time: "2025-03-28T07:00:00Z",
    return_time: "2025-03-28T15:30:00Z",
    available_seats: 4,
    price: 20,
    description: "Day trip to Seymour. Easy going group.",
    car_make: "Ford",
    car_model: "Explorer",
    gear_space: "Large - plenty of room for gear",
    created_at: "2025-03-10T08:50:00Z"
  },
  {
    id: "1007",
    driver_id: "user111",
    departure_location: "West Vancouver",
    destination: "Whistler Blackcomb",
    ski_resort: "Whistler Blackcomb",
    pickup_zone: "Park Royal Mall",
    departure_time: "2025-03-30T06:30:00Z",
    return_time: "2025-03-30T19:00:00Z",
    available_seats: 1,
    price: 50,
    description: "Solo driver looking for company on Whistler trip.",
    car_make: "BMW",
    car_model: "X3",
    gear_space: "Medium - room for 2 snowboards",
    created_at: "2025-03-12T16:25:00Z"
  },
  {
    id: "1008",
    driver_id: "user222",
    departure_location: "Richmond",
    destination: "Cypress Mountain",
    ski_resort: "Cypress Mountain",
    pickup_zone: "Richmond Centre",
    departure_time: "2025-04-01T16:00:00Z",
    return_time: "2025-04-01T22:00:00Z",
    available_seats: 3,
    price: 25,
    description: "After work shred session. Join the fun!",
    car_make: "Volkswagen",
    car_model: "Tiguan",
    gear_space: "Medium - fits 3 sets of gear comfortably",
    created_at: "2025-03-15T10:10:00Z"
  },
  {
    id: "1009",
    driver_id: "user333",
    departure_location: "Coquitlam",
    destination: "Mount Baker",
    ski_resort: "Mount Baker",
    pickup_zone: "Coquitlam Centre",
    departure_time: "2025-04-03T05:45:00Z",
    return_time: "2025-04-03T20:00:00Z",
    available_seats: 2,
    price: 60,
    description: "Full day at Baker. Early start for border crossing.",
    car_make: "Nissan",
    car_model: "Pathfinder",
    gear_space: "Large - room for all your gear",
    created_at: "2025-03-18T13:30:00Z"
  },
  {
    id: "1010",
    driver_id: "user444",
    departure_location: "Seattle Downtown",
    destination: "Stevens Pass",
    ski_resort: "Stevens Pass",
    pickup_zone: "Space Needle",
    departure_time: "2025-04-04T07:15:00Z",
    return_time: "2025-04-04T18:30:00Z",
    available_seats: 3,
    price: 40,
    description: "Regular weekend warrior trip to Stevens.",
    car_make: "Hyundai",
    car_model: "Santa Fe",
    gear_space: "Medium - standard gear space",
    created_at: "2025-03-20T09:45:00Z"
  },
  {
    id: "1011",
    driver_id: "user555",
    departure_location: "Bellevue",
    destination: "Snoqualmie Pass",
    ski_resort: "Snoqualmie Pass",
    pickup_zone: "Bellevue Square",
    departure_time: "2025-04-05T08:30:00Z",
    return_time: "2025-04-05T17:00:00Z",
    available_seats: 4,
    price: 30,
    description: "Family-friendly trip to Snoqualmie.",
    car_make: "Kia",
    car_model: "Sorento",
    gear_space: "Large - room for family gear",
    created_at: "2025-03-22T15:55:00Z"
  },
  {
    id: "1012",
    driver_id: "user666",
    departure_location: "Vancouver UBC",
    destination: "Whistler Blackcomb",
    ski_resort: "Whistler Blackcomb",
    pickup_zone: "UBC Campus",
    departure_time: "2025-04-06T07:00:00Z",
    return_time: "2025-04-06T19:30:00Z",
    available_seats: 3,
    price: 45,
    description: "Student discount on lift tickets! Join us.",
    car_make: "Subaru",
    car_model: "Forester",
    gear_space: "Medium-Large - good for multiple boards",
    created_at: "2025-03-25T17:20:00Z"
  },
  {
    id: "1013",
    driver_id: "user777",
    departure_location: "North Seattle",
    destination: "Crystal Mountain",
    ski_resort: "Crystal Mountain",
    pickup_zone: "Northgate Mall",
    departure_time: "2025-04-08T06:00:00Z",
    return_time: "2025-04-08T18:00:00Z",
    available_seats: 2,
    price: 45,
    description: "Mid-week powder day! Taking time off work.",
    car_make: "Chevrolet",
    car_model: "Tahoe",
    gear_space: "Large - tons of room for gear",
    created_at: "2025-03-27T14:10:00Z"
  },
  {
    id: "1014",
    driver_id: "user888",
    departure_location: "Portland East",
    destination: "Mount Bachelor",
    ski_resort: "Mount Bachelor",
    pickup_zone: "Lloyd Center",
    departure_time: "2025-04-10T05:30:00Z",
    return_time: "2025-04-10T21:00:00Z",
    available_seats: 3,
    price: 70,
    description: "Long day trip to Bachelor. Amazing views!",
    car_make: "GMC",
    car_model: "Yukon",
    gear_space: "Extra Large - room for gear and luggage",
    created_at: "2025-03-29T08:35:00Z"
  },
  {
    id: "1015",
    driver_id: "user999",
    departure_location: "Downtown Seattle",
    destination: "Mount Rainier",
    ski_resort: "Mount Rainier National Park",
    pickup_zone: "Pike Street",
    departure_time: "2025-04-11T08:45:00Z",
    return_time: "2025-04-11T18:15:00Z",
    available_seats: 4,
    price: 50,
    description: "Scenic trip to Rainier. Experienced skiers preferred.",
    car_make: "Land Rover",
    car_model: "Discovery",
    gear_space: "Large - premium gear space",
    created_at: "2025-04-01T12:15:00Z"
  },
  {
    id: "1016",
    driver_id: "user123",
    departure_location: "Vancouver Downtown",
    destination: "Cypress Mountain",
    ski_resort: "Cypress Mountain",
    pickup_zone: "Canada Place",
    departure_time: "2025-04-12T14:00:00Z",
    return_time: "2025-04-12T21:00:00Z",
    available_seats: 2,
    price: 25,
    description: "Quick afternoon session at Cypress.",
    car_make: "Subaru",
    car_model: "Outback",
    gear_space: "Medium - can fit 3 sets of skis",
    created_at: "2025-04-02T09:50:00Z"
  },
  {
    id: "1017",
    driver_id: "user456",
    departure_location: "Seattle",
    destination: "Stevens Pass",
    ski_resort: "Stevens Pass",
    pickup_zone: "University District",
    departure_time: "2025-04-13T07:30:00Z",
    return_time: "2025-04-13T17:30:00Z",
    available_seats: 3,
    price: 40,
    description: "Last chance for spring skiing at Stevens!",
    car_make: "Toyota",
    car_model: "4Runner",
    gear_space: "Large - room for boards and skis",
    created_at: "2025-04-03T16:40:00Z"
  },
  {
    id: "1018",
    driver_id: "user789",
    departure_location: "Portland",
    destination: "Timberline Lodge",
    ski_resort: "Timberline Lodge",
    pickup_zone: "Downtown Portland",
    departure_time: "2025-04-14T06:15:00Z",
    return_time: "2025-04-14T19:45:00Z",
    available_seats: 4,
    price: 55,
    description: "All day spring skiing adventure at Timberline.",
    car_make: "Honda",
    car_model: "Pilot",
    gear_space: "Large - fits all your gear plus coolers",
    created_at: "2025-04-05T11:25:00Z"
  },
];

// Create CSV content
const header = 'id,driver_id,departure_location,destination,ski_resort,pickup_zone,departure_time,return_time,available_seats,price,description,car_make,car_model,gear_space,created_at';
const rows = rides.map(ride => {
  return [
    ride.id,
    ride.driver_id,
    ride.departure_location,
    ride.destination,
    ride.ski_resort,
    ride.pickup_zone,
    ride.departure_time,
    ride.return_time,
    ride.available_seats,
    ride.price,
    `"${ride.description}"`,
    ride.car_make,
    ride.car_model,
    `"${ride.gear_space}"`,
    ride.created_at
  ].join(',');
});

const csvContent = [header, ...rows].join('\n');

// Write to file
fs.writeFileSync('rides_sample.csv', csvContent);

console.log('CSV file generated successfully: rides_sample.csv'); 